const Map<String, String> enUS = {
  'hello': 'Hello',
  'welcome': 'Welcome',
  'Home':'Home',
  'Quick Action':'Quick Action',
  'Select Language':'Select Language',
  'Recent Purchase Order':'Recent Purchase Order',
  'Recent Sale Order':'Recent Sale Order',
  'View All':'View All',
  'Login':'Login',
  'Enter username': 'Enter username',
  'Enter password': 'Enter password',
  'Good Morning 👋': 'Good Morning 👋',
  'Good Afternoon': 'Good Afternoon',
  'Good Evening': 'Good Evening',
  'Good Night': 'Good Night',
  'Welcome Back': 'Welcome Back',
  'Sale':'Sale',
  'Category':'Category',
  'Product':'Product',
  'Supplier':'Supplier',
  'Qty':'Qty',
  'Price':'Price',
  'Date':'Date',
  'Purchase':'Purchase',
  'Category Management':'Category Management',
  'Customer':'Customer',
  'Audit Logs':'Audit Logs',
  'Stock Adjustment': 'Stock Adjustment',
  'Stock Transfer': 'Stock Transfe',
  'Warehouse': 'Warehouse',
  'Sale List': 'Sale List',
  'Sale Payment': 'Sale Payment',
  'Role': 'Role',
  'User': 'User',
  'Product & Category Management': 'Product & Category Management',
  'Search Category':'Search Category',
  'Add Category':'Add Category',
  'Edit Category':'Edit Category',
  'Category Name': 'Category Name',
  'Icon': 'Icon',
  'Description':'Description',
  'Enter Category Name': 'Enter Category Name',
  'Enter Description': 'Enter Description',
  'Enter Icon':'Enter Icon',
  'Save':'Save',
  'Delete':'Delete',
  'Edit':'Edit',
  'Search Product':'Search Product',
  'Add Product':'Add Product',
  'Pick Image':'Pick Image',
  'Enter Category':'Enter Category',
  'Select Category':'Select Category',
  'Product Name': 'Product Name',
  'Enter Product Name': 'Enter Product Name',
  'Select Supplier':'Select Supplier',
  'Barcode':'Barcode',
  'Enter Barcode':'Enter Barcode',
  'Cost Price':'Cost Price',
  'Enter Cost Price':'Enter Cost Price',
  'Sale Price': 'Sale Price',
  'Enter Sale Price':'Enter Sale Price',
  'Quantity':'Quantity',
  'Enter Quantity':'Enter Quantity',
  'Unit':'Unit',
  'Select Unit':'Select Unit',
  'Product Detail':'Product Detail',
  'Edit Product':'Edit Product',
  'Total Purchases':'Total Purchases',
  'Purchases':'Purchases',
  'Search Purchases...':'Search Purchases...',
  'Search Suppliers':'Search Suppliers',
  'Suppliers':'Suppliers',
  'Add Supplier':'Add Supplier',
  'Supplier Name':'Supplier Name',
  'Enter Supplier Name':'Enter Supplier Name',
  'Phone Number':'Phone Number',
  'Enter Phone Number':'Enter Phone Number',
  'Email':'Email',
  'Enter Email':'Enter Email',
  'Map': 'Map',
  'Enter Map': 'Enter Map',
  'Address': 'Address',
  'Enter Address': 'Enter Address',
  'Status': 'Status',
  'No supplier data found':'No supplier data founds',
  'Supplier Detail':'Supplier Detail',
  'Supplier Information': 'Supplier Information',
  'Created': 'Created',
  'Edit Supplier':'Edit Supplier',
  'Search Customers by name or ID':'Search Customers by name or ID',
  'Total Customers':'Total Customers',
  'Active Customers':'Active Customers',
  'Inactive Customers':'Inactive Customers',
  'Customer Name':'Customer Name',
  'Add Customer':'Add Customer',
  'Enter Customer Name':'Enter Customer Name',
  'Edit Customer':'Edit Customer',
  'Search Stock Adjustment':'Search Stock Adjustment',
  'Select Product':'Select Product',
  'Select Warehouse':'Select Warehouse',
  'Add Stock Adjustment':'Add Stock Adjustment',
  'Adjustment Type': 'Adjustment Type',
  'Select Adjustment Type': 'Select Adjustment Type',
  'Increase': 'Increase',
  'Decrease': 'Decrease',
  'Reference NO': 'Reference NO',
  'Enter Reference Number': 'Enter Reference Number',
  'Previous Stock': 'Previous Stock',
  'Enter Previous Stock': 'Enter Previous Stock',
  'New Quantity': 'New Quantity',
  'Enter New Quantity': 'Enter New Quantity',
  'Reason': 'Reason',
  'Enter Reason': 'Enter Reason',
  'Stock Adjustment Detail': 'Stock Adjustment Detail',
  'Edit Stock Adjustment': 'Edit Stock Adjustment',
};