"""update purchases

Revision ID: efa0fcb67158
Revises: cf02f9be52c2
Create Date: 2026-09-01 17:00:03.429659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'efa0fcb67158'
down_revision: Union[str, Sequence[str], None] = 'cf02f9be52c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_items', 'cost_price',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('purchase_items', 'qty',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('purchase_items', 'subtotal',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('purchases', 'subtotal',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('purchases', 'tax_amount',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('purchases', 'discount_amount',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('purchases', 'total_amount',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('purchases', 'paid_amount',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('purchases', 'due_amount',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchases', 'due_amount',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('purchases', 'paid_amount',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('purchases', 'total_amount',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('purchases', 'discount_amount',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('purchases', 'tax_amount',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('purchases', 'subtotal',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('purchase_items', 'subtotal',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('purchase_items', 'qty',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('purchase_items', 'cost_price',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
